name: nightly-rubies-checks
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  nightly-rubies-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['head', '3.0', '3.1', '3.2']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Build and test with Rake
        env:
          BUGZILLA_API_KEY: ${{ secrets.BUGZILLA_API_KEY }}
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake
