name: Ruby
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: rspec_tests
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby 3.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
      - name: Build and test with Rake
        env:
          BUGZILLA_API_KEY: ${{ secrets.BUGZILLA_API_KEY }}
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake
      - name: Check `simplecov` result line coverage
        run: cat coverage/.last_run.json | jq '.result.line' | grep -q '100'
      - name: Check source files using `rubocop`
        run: bundle exec rubocop
      - name: Check that code 100% documented
        run: yardoc . | grep -q '100.00% documented'
